### ISSUE TITLE
crash with latest version

### ISSUE THREAD

**Issue by raltus** [Sirttas/DataPack-Anvil#1]
I updated several mods, but when I went lo load it crashed and this came up. I did run it again after updating forge to see if it happened again, then downgraded to the last version.

Failure message: DataPack Anvil (dpanvil) encountered an error during the process_imc event phase
		java.lang.NoSuchFieldError: BLOCK_PREDICATE

[crash-2021-03-10_19.24.29-fml.txt](https://github.com/Sirttas/DataPack-Anvil/files/6119844/crash-2021-03-10_19.24.29-fml.txt)

**Comment by Sirttas** [comment]
In 1.1 I removed deprecated code thinking that it was not used by latest version of elemental craft. Downgrading to 1.0.10 should work.

**Comment by Sirttas** [comment]
fixed in 1.1.2
