### ISSUE TITLE
[1.17.1] Crash when launching Minecraft on Forge 37.0.53

### ISSUE THREAD

**Issue by Gbergz** [Sirttas/DataPack-Anvil#3]
**Describe the bug**
Game is crashing when attempting to launch mod on Forge version 37.0.53

**To Reproduce**
1. Install DP Anvil
2. Install Forge 37.0.53
3. Start the game.
4. Crash.

**Expected behavior**
That the game doesn't crash when attempting to launch it.

**Versions**
Minecraft: 1.17.1
Forge: 37.0.53
DP Anvil: 2.0.2 | https://www.curseforge.com/minecraft/mc-mods/datapack-anvil/files/3418098

**ModPack**
No modpack. (modlist at the bottom of the crash report below.)

**Crash-Report**
https://gist.github.com/Gbergz/c1d515fb143fcfd419ef111fc39a9bdb

**Image**
![image](https://user-images.githubusercontent.com/26634554/132108913-22a28d5f-5155-4ee0-95ff-2eb1c8d45783.png)

**Comment by Sirttas** [comment]
Forge broke things, I will fix it tomorrow.

**Comment by Sirttas** [comment]
Fixed in 2.0.3
