### ISSUE TITLE
Reflection error log spam

### ISSUE THREAD

**Issue by jeremiahwinsley** [Sirttas/DataPack-Anvil#5]
**Describe the bug**
dpanvil 1.2.3 has a lot of reflection errors in the logs:

https://gist.github.com/jeremiahwinsley/26403ebae58cc4e8fac7365b283508e3

**To Reproduce**
1. Install ElementalCraft and dependencies in a fresh instance of Forge 36.2.8.
2. Launch the game, then look at `latest.log`.

**Comment by Sirttas** [comment]
Caused by java 12+ (https://bugs.openjdk.java.net/browse/JDK-8210522). It's a known problem but fixed it in MC 1.17 but I won't be able to fix it for 1.16.
