### ISSUE TITLE
1.19.2, forge 41.1.16, server and client crash at launch

### ISSUE THREAD

**Issue by Daltaxy** [Sirttas/DataPack-Anvil#7]
**Describe the bug**
Server and client crash at launch with the mod installed. I know Supplementaries is also there, but I don't think there is a link ? I already posted an issue for that mod.
debug.log + crash report : https://gist.github.com/Daltaxy/cac1323e0e53e7f7c5352634e8836b11
**To Reproduce**
Start the game with the mod installed. Yesterday everything was fine so it is either due to forge, or elementalcraft, which had an update yesterday. Note that reverting back to the older (the one before the latest) version of ElementalCraft did not fix the issue.

**Expected behavior**
no crash; everything worked fine yesterday
**ModPack**
Either a known pack (ex: ATM6) or a Twitch/MultiMC export
own mod selection

**Comment by Sirttas** [comment]
`org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [ae2ao.mixins.json:PlayerListMixin] from phase [DEFAULT] in config [ae2ao.mixins.json] FAILED during APPLY`

ae2ao mixins seems to be broken. there is a good chance this is the cause.

**Comment by Daltaxy** [comment]
> `org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [ae2ao.mixins.json:PlayerListMixin] from phase [DEFAULT] in config [ae2ao.mixins.json] FAILED during APPLY`
> 
> ae2ao mixins seems to be broken. there is a good chance this is the cause.

thank you. I'm sorry. I have no idea why the logs, at first sight, indicate these mods.
Anyways, yeah, removing it fixed the problem. thank you again
