### ISSUE TITLE
DPanvil crashing on 1.19.2 Forge version 43.1.47

### ISSUE THREAD

**Issue by daniel56483** [Sirttas/DataPack-Anvil#8]
**Describe the bug**
When booting up my modpack i go to create a new world and it crashes

**To Reproduce**
1.Load the modpack up
2.Go to create a new world
3. crashes
[latest.log](https://github.com/Sirttas/DataPack-Anvil/files/10048032/latest.log)

**Expected behavior**
Its suppose to pull up the menu to create a new minecraft world.

**ModPack**
(wont let me upload the pack to github as it is 1642MB )

**Comment by HockeyZman2000** [comment]
[latest.log](https://github.com/Sirttas/DataPack-Anvil/files/10361191/latest.log)

I've got something similar going on here

**Comment by Sirttas** [comment]
Both crashes seems to be caused by broken datapacks.
