### ISSUE TITLE
[1.20.1] Disconnect when joining server. (Exception caught in connection handler!)

### ISSUE THREAD

**Issue by Gbergz** [Sirttas/DataPack-Anvil#9]
**Describe the bug**
Joining server results in a disconnect.
(Missing tag TagKey[minecraft:item / elementalcraft:pure_ores/sources/raw_uraninite)

**To Reproduce**
1. Make a server
2. Add elementalcraft
3. Disconnect.
4. See error.

**Logs/Disconnect error**:
https://gist.githubusercontent.com/Gbergz/54083efeb45bbc4c5f121bf509dd6ec7/raw/750bd620d5df5ac52272a0531e90b48cd620f354/gistfile1.txt

**Expected behavior**
Joining a server without disconnect.

**ModPack**
TNP Limitless 7, but an unreleased version. Testing.

**Versions**
ElementalCraft: 6.0.0b
DP Anvil: 5.0.0c
Forge: 47.1.3
Minecraft: 1.20.1

**Comment by Sirttas** [comment]
This is an issue with dp anvil so I'm moving it to the proper project, it will be fixed later today.

**Comment by Sirttas** [comment]
Fixed in 5.0.1

**Comment by Gbergz** [comment]
This version isn't released yet?

**Comment by Sirttas** [comment]
it is: https://legacy.curseforge.com/minecraft/mc-mods/datapack-anvil/files/4795000

**Comment by Gbergz** [comment]
Nevermind, it wasn't marked as Forge (only Neo) so it didn't show up in Launchers.

**Comment by Gbergz** [comment]
Fixed now, thanks!
